### ISSUE TITLE
I look for auroras near me

### ISSUE THREAD

**Issue by ReedGigabyte** [AllegrettoAdam/aurora-me#17]
As a user, I should be able to see a list of places near me to see auroras

Acceptance criteria: As a user, I can click on the finder page and be given my chance of seeing an aurora with locations that are close to me and the chances of seeing an aurora there

**Comment by AllegrettoAdam** [comment]
Completed. Final implementation varies from the specifics here, but fulfills the same core functionality described in the Acceptance Criteria.
